# Generated by Django 2.0.4 on 2018-04-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_solar_congig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solar_congig',
            new_name='solar_config',
        ),
    ]
