# Generated by Django 2.0.4 on 2018-04-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_auto_20180411_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solar_config',
            old_name='time_zone',
            new_name='time_zone1',
        ),
        migrations.AddField(
            model_name='solar_config',
            name='time_zone2',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
