# Generated by Django 2.0.4 on 2018-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_auto_20180411_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solar_Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('p_mp', models.FloatField()),
            ],
        ),
    ]
