# Generated by Django 2.0.4 on 2018-04-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0010_auto_20180419_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar_forecast',
            name='time_zone',
            field=models.CharField(default='EUrope/Stockhome', max_length=100),
            preserve_default=False,
        ),
    ]
