# Generated by Django 2.0.4 on 2018-04-27 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0011_solar_forecast_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='battery_config_data',
            name='time0',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 27, 6, 58, 39, 802103)),
        ),
    ]
