# Generated by Django 2.0.4 on 2018-04-27 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0012_auto_20180427_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='energy_dsm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battery_config_data',
            name='time0',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 27, 11, 31, 4, 61663)),
        ),
    ]
